### PR TITLE
responsive navbar added

### PR DESCRIPTION
**Pull request by MikiyasWT**

### CODE REVIEW

**Comment by frectonz** [comment]
Could you attach screenshots so we can see the changes visually

**Comment by frectonz** [comment]
I see that you have included a `package-lock.json` in your commit. We use `pnpm` on this project and i think you used `npm` to install the packages so can you remove the `package-lock.json` from your commit.

**Comment by MikiyasWT** [comment]
Screenshot_select-area_20230410143246
Screenshot_select-area_20230410143306
Screenshot_select-area_20230410143344

**Comment by MikiyasWT** [comment]
alright i will remove it

**Comment by frectonz** [comment]
The nav is only visible in small screens right and can you turn the dropdown into an element that covers the full page and lists the links.

**Review by baydisng13 — APPROVED** [review]
Nice job guys 👏
Let's go street deployment

**Pull request merged**
