### PR TITLE
Standardized type defs and added a Meta component

### PR DESCRIPTION
**Pull request by k4l3b4**
As asked i merged the updated main repo woth my fork and remade the previous changed for reminder:- through out the app there were many ways types were passed to the component so i standardized all of them to be the same and also added a Meta component that has all the necessary data and passable data

I have done all pre commit checks and my code passes all but the code that i forked and cloned had issues according to rome's standards, some with using `` for strings and also using the index number as a key.

I would also recommend when making reusable components it's better to put them in their own folder, and if the website is going to grow and have many pages i recommend putting the pages in their own folder as well.

### CODE REVIEW

**Comment by k4l3b4** [comment]
> Nice, can you add some test cases for the meta component if possible.

okay on it

**Comment by k4l3b4** [comment]
> Nice, can you add some test cases for the meta component if possible.



> Nice, can you add some test cases for the meta component if possible.

A little confused, i would write test cases for it but, the project doesn't use any testing packages, so how do you advise me to write the committable tests??

**Comment by hope-miky** [comment]
> > Nice, can you add some test cases for the meta component if possible.
> 
> 
> 
> A little confused, i would write test cases for it but, the project doesn't use any testing packages, so how do you advise me to write the committable tests??

@frectonz @baydisng13 any thoughts?

**Comment by k4l3b4** [comment]
> > > Nice, can you add some test cases for the meta component if possible.
> > 
> > 
> > A little confused, i would write test cases for it but, the project doesn't use any testing packages, so how do you advise me to write the committable tests??
> 
> @frectonz @baydisng13 any thoughts?

guessing it isn't taken really seriously.

**Comment by frectonz** [comment]
Sorry for the late response, but from what i can see you made code quality improvements. and it is kind of hard to see the changes you have made since you run the formatting affected everything

**Comment by k4l3b4** [comment]
> Sorry for the late response, but from what i can see you made code quality improvements. and it is kind of hard to see the changes you have made since you run the formatting affected everything

not a problem, yeah your right, only did it because i read it in the pre-commit.yaml file, i tested the app locally and it works perfectly

**Comment by k4l3b4** [comment]
> Sorry for the late response, but from what i can see you made code quality improvements. and it is kind of hard to see the changes you have made since you run the formatting affected everything

i could try to reverse the formatting and recommit the changes if needed

**Review by frectonz — APPROVED** [review]
:+1:

**Comment by frectonz** [comment]
I am seeing some merge conflicts can you add a commit that syncs you up with the `main` branch

**Comment by k4l3b4** [comment]
> I am seeing some merge conflicts can you add a commit that syncs you up with the `main` branch

sure

**Pull request closed without merging**
